apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-dbconfigmap
data:
  # property-like keys; each key maps to a simple value
  mysql_database: phonebook
  mysql_user: pauls
  mysql_database_host: mysql-service