apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  mysql_password: UGF1bF8xMjM0NTY3ODk=  #Paul_123456789
  mysql_root_password: UGF1bEtlbGxlcm1hbl8xMjM0NTY3ODk=  #PaulKellerman_123456789