apiVersion: v1
kind: Service
metadata:
  name: result-server-service
  labels:
    app: result-server-service
spec:
  type: NodePort 
  ports:
  - port: 80  
    targetPort: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: result-server-pod
    
