apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    app: web-server-service
spec:
  type: NodePort 
  ports:
  - port: 80  
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: web-server-pod
    
